version: '3.8'

# Port number reservations:
# 8000 ~ 8099: Reserved for host
# 8100 ~ 8199: Reserved for Eason
# 8200 ~ 8299: Reserved for SeFo
# 8300 ~ 8399: Reserved for Hong Wang

# Note:
# Don't forget excute `sudo ufw allow {PORT_NUMBER}` to open the port for firewall.

services:
  # Eason
  eason.nextcloud.db:
    image: mariadb:10.5
    restart: always
    networks:
      - eason
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - eason.nextcloud.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${EASON_NEXTCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${EASON_NEXTCLOUD_DB_USER_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloudAdmin
  eason.nextcloud.app:
    image: nextcloud:26.0.0-apache
    restart: always
    networks:
      - eason
    ports:
      - "127.0.0.1:8180:80"
    links:
      - eason.nextcloud.db
    volumes:
      - eason.nextcloud:/var/www/html
      - ${EASON_NEXTCLOUD_DATA_DIRECTORY}:/var/www/html/data
    environment:
      - APACHE_DISABLE_REWRITE_IP={EASON_NEXTCLOUD_APACHE_DISABLE_REWRITE_IP}
      - MYSQL_PASSWORD=${EASON_NEXTCLOUD_DB_USER_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloudAdmin
      - MYSQL_HOST=eason.nextcloud.db
      - NEXTCLOUD_ADMIN_USER=${EASON_NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${EASON_NEXTCLOUD_ADMIN_USER_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${EASON_NEXTCLOUD_TRUSTED_DOMAINS}  # space-separated list of domains
      - TRUSTED_PROXIES=${EASON_NEXTCLOUD_TRUSTED_PROXIES}  # space-separated list of domains

  # SeFo
  sefo.ubuntu20-cuda11:
    build:
      context: ./services/cuda-11.7-ubuntu-20.04
      args:
        - ROOT_PASSWORD=${SEFO_CUDA_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - sefo
    ports:
      - "8220:22"
    volumes:
      - ./keys/sefo-ssh-keys:/root/.ssh/authorized_keys
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # Hong Wang

networks:
  eason:
    driver: bridge
  sefo:
    driver: bridge
  hongwang:
    driver: bridge

volumes:
  eason.nextcloud:
  eason.nextcloud.db:
